[package]
name = "gfc"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.87"
async-trait = "0.1.82"
bollard = "0.17.1"
futures-util = "0.3.30"
tokio = { version = "1.40.0", features = ["rt", "rt-multi-thread", "macros"] }
