server:
  host: 0.0.0.0
  port: 3080

workspace:
  manifests_root: resources/projects # where project files are stored
  repositories_root: resources/repositories # where repositories are cloned

telemetry:
  enabled: true
  service_name: gfc
  otlp_endpoint: http://localhost:4317
  log_level: info
  excluded_modules:
    - hyper
    - tonic
    - h2
    - reqwest
    - opentelemetry
